// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCow891-PDQoFx5h97KMa2y6NxOJORa800',
    appId: '1:672829287029:android:9ae486805a2934d726263c',
    messagingSenderId: '672829287029',
    projectId: 'fitguide-christoph',
    storageBucket: 'fitguide-christoph.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2RzKrCiFIMT_IsHY-WCt62O46TAj41jo',
    appId: '1:672829287029:ios:eb0d8afdc9e48b6026263c',
    messagingSenderId: '672829287029',
    projectId: 'fitguide-christoph',
    storageBucket: 'fitguide-christoph.firebasestorage.app',
    iosBundleId: 'com.example.fitguide',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU0KH1fn38XddixqTs5cRzoQQJ37uhCfI',
    appId: '1:672829287029:web:ecc4308139e0d13b26263c',
    messagingSenderId: '672829287029',
    projectId: 'fitguide-christoph',
    authDomain: 'fitguide-christoph.firebaseapp.com',
    storageBucket: 'fitguide-christoph.firebasestorage.app',
    measurementId: 'G-NNTHCH46W0',
  );

}